# Generated by Django 4.1.3 on 2022-12-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
